//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://bit.ly/reswcodegen)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 05/21/2018 15:51:04
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Seismograph
{
    using Windows.ApplicationModel.Resources;
    
    
    public sealed partial class AppResources
    {
        
        private static ResourceLoader resourceLoader;
        
        static AppResources()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(AppResources).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = ResourceLoader.GetForCurrentView("AppResources");
            }
            else
            {
                resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/AppResources");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "About"
        /// </summary>
        public static string AboutCommandCaption
        {
            get
            {
                return resourceLoader.GetString("AboutCommandCaption");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No accelerometer was found.  Try running this app on a Microsoft Surface tablet."
        /// </summary>
        public static string AccelerometerNotFound
        {
            get
            {
                return resourceLoader.GetString("AccelerometerNotFound");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Seismograph"
        /// </summary>
        public static string DefaultDataFileName
        {
            get
            {
                return resourceLoader.GetString("DefaultDataFileName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Snapshot"
        /// </summary>
        public static string DefaultSnapshotFileName
        {
            get
            {
                return resourceLoader.GetString("DefaultSnapshotFileName");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Snapshot Error"
        /// </summary>
        public static string ErrorSavingSnapshotCaption
        {
            get
            {
                return resourceLoader.GetString("ErrorSavingSnapshotCaption");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "OK"
        /// </summary>
        public static string OkCaption
        {
            get
            {
                return resourceLoader.GetString("OkCaption");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Privacy Policy"
        /// </summary>
        public static string PrivacyCommandCaption
        {
            get
            {
                return resourceLoader.GetString("PrivacyCommandCaption");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Remove Ads Failed"
        /// </summary>
        public static string RemoveAdsFailedCaption
        {
            get
            {
                return resourceLoader.GetString("RemoveAdsFailedCaption");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Settings"
        /// </summary>
        public static string SettingsCommandCaption
        {
            get
            {
                return resourceLoader.GetString("SettingsCommandCaption");
            }
        }
    }
}
